name: ChatEssentials
version: "1.0.0"
main: ChatEssentials.Main
api : ["1.0.9"]
commands :
  chat:
    description: Main Chat Manager Command.
    alliases: [c, ch]
    permission: chat.help
  clearchat:
    description: ClearChat command
    aliases: [cc]
    permission: chat.clearchat
  mutechat:
    description: MuteChat command
    permission: chat.mutechat

